# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pushify}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Tillery"]
  s.date = %q{2011-01-20}
  s.default_executable = %q{pushify}
  s.email = %q{tilleryj@thinklinkr.com}
  s.executables = ["pushify"]
  s.files = [
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/pushify",
    "install/expressinstall.swf",
    "install/json.js",
    "install/juggernaut.js",
    "install/juggernaut.swf",
    "install/juggernaut.yml",
    "install/juggernaut_hosts.yml",
    "install/pushify.js",
    "install/swfobject.js",
    "lib/pushify.rb",
    "lib/pushify/helper.rb",
    "lib/pushify/install.rb",
    "lib/pushify/juggernaut.rb",
    "lib/pushify/rack.rb",
    "lib/pushify/rails.rb",
    "lib/pushify/server.rb",
    "pushify.gemspec"
  ]
  s.homepage = %q{http://github.com/tilleryj/pushify}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{See updates you make to css, html, javascript, and images appear immediately in all of your browsers without having to refresh.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

