# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pushify}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Tillery"]
  s.date = %q{2010-10-22}
  s.email = %q{tilleryj@gmail.com}
  s.files = [
    "LICENSE",
     "README.markdown",
     "ROADMAP",
     "Rakefile",
     "VERSION",
     "bin/csspush",
     "bin/pushify",
     "install/css_push.js",
     "install/css_push_initializer.rb",
     "install/expressinstall.swf",
     "install/juggernaut.js",
     "install/juggernaut.swf",
     "install/juggernaut.yml",
     "install/juggernaut_hosts.yml",
     "install/swfobject.js",
     "lib/css_push_server.rb",
     "rails/init.rb",
     "spec/css_push_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/tilleryj/pushify}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{See updates you make to css files appear immediately in all of your browsers without having to refresh.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

